name: Build, Test and Deploy
on: [ push, workflow_dispatch ]

jobs:

  build:
    name: Determine images
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build dist
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    needs: build
    outputs:
      matrix: ${{ steps.get-variants.outputs.matrix }}
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      
      - name: Get list of variants for an image
        id: get-variants
        run: echo "::set-output name=matrix::$(jq -c '.variants' ./dist/variant-matrix.json)"

  # test:
  #   name: Run test on image
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   strategy:
  #     matrix:
  #       variant: ${{ fromJson(needs.setup.outputs.matrix) }}
  #     fail-fast: false
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run test for ${{ matrix.variant.IMAGE }}
  #       env:
  #         VARIANT: ${{ matrix.variant.VERSION }}
  #       run: test/${{ matrix.variant.IMAGE }}/test.sh

  publish:
    name: Publish image
    runs-on: ubuntu-latest
    needs: 
     - setup
    #  - test
    strategy:
      matrix:
        variant: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false
    steps:

      - name: Build devcontainer
        run: |
          echo "starting devcontainer build..."
          devcontainer build \
            --workspace-folder dist/${{ matrix.variant.IMAGE }}/${{ matrix.variant.VERSION }}/  \
            --image-name ghcr.io/The-Nefarious-Developer/${{ matrix.variant.IMAGE }}:${{ matrix.variant.VERSION }} \
            # --no-cache true

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install devcontainer cli
  #       run: npm install -g @devcontainers/cli

  #     - name: Build image ${{ matrix.template }}/${{ matrix.variant }}
  #       env:
  #         TEMPLATE: ${{ matrix.template }}
  #         VARIANT: ${{ matrix.variant }}
  #       run: scripts/build.sh

  #     # - name: Build devcontainer
  #     #   run: |
  #     #     echo "starting devcontainer build..."
  #     #     devcontainer build \
  #     #       --workspace-folder tmp/src/${{ matrix.template }}/${{ matrix.variant }}/  \
  #     #       --image-name ghcr.io/The-Nefarious-Developer/${{ matrix.template }}:${{ matrix.variant }} \
  #     #       # --no-cache true